Repository MUSINSSAK/front-end, pull requests merged in 2025-09, with the labels that each got.

#26 Feat: 비밀번호 유효성 검사 구현 및 규칙 변경
  src/pages/FindPassword/FindPassword.tsx
  src/pages/SignUp/SignUp.tsx
Labels: ✨ FEAT

#27 Feat: JWT 토큰 자동 재발급 및 연장 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/authApi.ts
  src/hooks/useTokenExpirationCheck.ts
  src/lib/axios.ts
Labels: ✨ FEAT

#31 Feat: 챗봇 UI 및 API 연동 기능 구현
  src/App.tsx
  src/api/chat.ts
  src/components/organisms/ChatWidget/ChatWidget.module.css
  src/components/organisms/ChatWidget/ChatWidget.tsx
  src/types/chat.ts
Labels: ✨ FEAT, 🔧 CHORE

#32 Feat: 마이페이지 주문 내역 조회 UI 구현
  src/api/orderApi.ts
  src/components/organisms/OrderHistorySection/OrderHistorySection.module.css
  src/components/organisms/OrderHistorySection/OrderHistorySection.tsx
  src/types/order.ts
Labels: ✨ FEAT

#33 Feat: 상품 상세 페이지 UI 제작
  src/components/atoms/RatingStars/RatingStars.tsx
  src/components/atoms/index.ts
  src/components/molecules/ImageGallery/ImageGallery.module.css
  src/components/molecules/ImageGallery/ImageGallery.tsx
  src/components/molecules/ReviewItem/ReviewItem.module.css
  src/components/molecules/ReviewItem/ReviewItem.tsx
  src/components/molecules/SizeSelect/SizeSelect.module.css
  src/components/molecules/SizeSelect/SizeSelect.tsx
  src/components/molecules/TabNav/TabNav.module.css
  src/components/molecules/TabNav/TabNav.tsx
  src/components/molecules/index.ts
  src/components/organisms/ProductInfoPanel/ProductInfoPanel.module.css
  src/components/organisms/ProductInfoPanel/ProductInfoPanel.tsx
  src/components/organisms/ProductReview/ProductReview.tsx
  src/components/organisms/ProductReview/ReviewsSection.module.css
  src/components/organisms/QASection/QASection.module.css
  src/components/organisms/QASection/QASection.tsx
  src/components/organisms/ReviewsSection/ReviewsSection.tsx
  src/components/organisms/ShippingReturnSection/ShippingReturnSection.module.css
  src/components/organisms/ShippingReturnSection/ShippingReturnSection.tsx
  src/components/organisms/StickyActionBar/StickyActionBar.module.css
  src/components/organisms/StickyActionBar/StickyActionBar.tsx
  src/components/organisms/index.ts
  src/components/templates/ProductDetailTemplate/ProductDetailTemplate.module.css
  src/components/templates/ProductDetailTemplate/ProductDetailTemplate.tsx
  src/components/templates/index.ts
  src/pages/ProductDetail/ProductDetail.module.css
  src/pages/ProductDetail/ProductDetail.tsx
  src/types/review.ts
  src/types/types.ts
Labels: ✨ FEAT, ♻️ REFACTOR
